### ISSUE TITLE
build.py error

### ISSUE THREAD

**Issue by futurist** [HsOjo/UnlockerX#8]
When run `python3 build.py`, below error thrown:

```
Traceback (most recent call last):
  File "/Users/jm/tools/UnlockerX/tools/translate/api/google.py", line 98, in _translate
    line_t = self.__translate(lang_from, lang_to, line)
  File "/Users/jm/tools/UnlockerX/tools/translate/api/google.py", line 29, in __translate
    [tkk] = re.findall(r"tkk:'([\d\\.]*)'", resp.text)
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/Users/jm/tools/UnlockerX/tools/translate/api/google.py", line 98, in _translate
    line_t = self.__translate(lang_from, lang_to, line)
  File "/Users/jm/tools/UnlockerX/tools/translate/api/google.py", line 29, in __translate
    [tkk] = re.findall(r"tkk:'([\d\\.]*)'", resp.text)
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by ordinary-hacker** [comment]
@futurist I have been trying to revive and revamp this project, and I think the best option is to get rid completely of Google translation and rather just use zhconv for translations. When I finish my fork and branch I'll do a PR, but for now you can replace this:
```python
# build translate language data.
Log.append('Build', 'Info', 'Building translate data now...')
load_language()
for lang_type in LANGUAGES.values():
    if issubclass(lang_type, TranslateLanguage):
        lang = lang_type()
        if not lang._translated:
            if lang._translate_to == 'cn_t':
                translator = zhconv()
            elif '--translate-baidu' in sys.argv:
                translator = baidu_translate()
            else:
                translator = google_translate()
            Log.append('Build', 'Translate', 'Using %s' % translator.__class__.__name__)

            lang.translate(translator)
            lang.save_current_translate()
        add_data(lang._data_path, './app/res/language/translate')
```

With this:
```python
# build translate language data.
Log.append('Build', 'Info', 'Building translate data now...')
load_language()
for lang_type in LANGUAGES.values():
    if issubclass(lang_type, TranslateLanguage):
        lang = lang_type()
        if not lang._translated:
            translator = None
            try:
                if lang._translate_to == 'cn_t':
                    translator = zhconv()
                elif '--translate-baidu' in sys.argv:
                    translator = baidu_translate()
                else:
                    # Only support zhconv for Chinese translations, skip others
                    if lang._translate_to in ['cn', 'cn_t']:
                        translator = zhconv()
                    else:
                        Log.append('Build', 'Warning', 'Skipping translation for %s (use --translate-baidu to enable)' % lang._translate_to)
                        continue
                
                if translator:
                    Log.append('Build', 'Translate', 'Using %s' % translator.__class__.__name__)
                    lang.translate(translator)
                    lang.save_current_translate()
            except Exception as e:
                Log.append('Build', 'Error', 'Translation failed for %s: %s' % (lang._translate_to, str(e)))
                Log.append('Build', 'Warning', 'Continuing build without translation for %s' % lang._translate_to)
        add_data(lang._data_path, './app/res/language/translate')
```

**Comment by ordinary-hacker** [comment]
Though in general I think it's better to straight up use hardcoded translations rather than complex logic with APIs.
